package rules;

import com.seongho.fds.dto.TransactionRequest;
import com.seongho.fds.dto.TransactionResponse;

global com.seongho.fds.dto.TransactionResponse response;

// 룰 1 : 1000만원 이상의 고액 송금은 "위험" 으로 간주
rule "High Amount Transfer Detection"
    when
        $tx : TransactionRequest(trusted == false , amount >= 10000000)
    then
        System.out.println("!!! [FDS 알림] 고액 송금 감지: " + $tx.getAmount() + "원");

        response.addReason("1000만원 이상의 고액 송금 감지");
        // 여기서 나중에 점수를 매기거나 차단 로직을 태움
end

// 룰 2 : 특정 국가(IP)에서의 접속 차단
rule "Blacklisted IP Detection"
    when
        // IP가 특정 대역(예: 192.168.0.x)으로 시작하는 경우를 위험으로 가정
        $tx : TransactionRequest(trusted == false, senderIp matches "192.168.0.*")
    then
        response.addReason("차단된 IP 대역으로부터의 접근입니다. ");

end

// 룰 3(상태기반 처리) : 1분 내에 5번 넘게 송금을 시도하는 경우

rule "High Frequency Transfer Detection"
    when
        // 1분 내에 5번 넘게 송금을 시도하는 경우
        $tx : TransactionRequest(trusted == false, recentTransactionCount >= 5)
    then
        response.addReason("단기간 반복 송금 감지 (1분 내 5회 이상)");
end